# 全局参数
company_name = "GlobalTech"
contact_email = "sales@globaltech-industries.com"
contact_phone = "+1-800-555-0199"
logo = "images/logo.jpg"

turnstile_site_key = "0x4AAAAAAB43R0lGyzeXeIiK"

# 社交媒体链接
[social]
  linkedin = "https://linkedin.com/company/globaltech"
  twitter = "https://twitter.com/globaltech"
  facebook = "https://facebook.com/globaltech"

# 热门文章数量
[blog.popular]
  limit = 3

[navigation]
  variant = "aurora"

  [navigation.cta]
    label = "Contact sales"
    url = "/contact/"
    newTab = false

  [navigation.search]
    enable = true
    placeholder = "Search the site"
    param = "q"
